# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 100Days
email: grahamgplace@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Graham Place
baseurl: "/100Days" # the subpath of your site, e.g. /blog
url: "www.graham.place/100Days" # the base hostname & protocol for your site
twitter_username: graham_place
github_username:  grahamplace
future: true

# Build settings
markdown: kramdown
